{{- if not .Values.registration.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localiam.fullname" . }}
  labels:
    {{- include "localiam.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.registration.secretKey }}: {{ include "localiam.registrationToken" . | b64enc | quote }}
{{- end }}
{{- if and .Values.shell.enabled .Values.shell.token (not .Values.shell.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localiam.shellSecret" . }}
  labels:
    {{- include "localiam.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.shell.secretKey }}: {{ .Values.shell.token | b64enc | quote }}
{{- end }}
{{- if .Values.bootstrapPrincipals }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localiam.fullname" . }}-principals
  labels:
    {{- include "localiam.labels" . | nindent 4 }}
type: Opaque
data:
  principals.json: {{ toJson .Values.bootstrapPrincipals | b64enc | quote }}
{{- end }}
